apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc
        - name: cloudsql-instance-credentials
          secret:
            secretName: db-credentials
      initContainers:
        - name: init-db
          image: google/cloud-sdk
          command: ['sh', '-c', 'gsutil cp gs://kube_database/init.sql /docker-entrypoint-initdb.d/init.sql && gsutil cp -r gs://kube_database/csvs/* /csvs/']
          volumeMounts:
            - name: db-data
              mountPath: /docker-entrypoint-initdb.d
            - name: cloudsql-instance-credentials
              mountPath: /secrets
              readOnly: true
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      