version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: moviesmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./csvs:/csvs
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: