version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: moviesmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - myappnet
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/csvs:/csvs
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./film_backend
    volumes:
      - ./film_backend:/app
    networks:
      - myappnet
    ports:
      - "12345:12345"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/moviesmanagement

networks:
  myappnet:
    driver: bridge

volumes:
  db_data: