apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filmcomments.fullname" . }}-frontend
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.selector.app }}
  replicas: {{ .Values.frontend.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.selector.app }}
    spec:
      containers:
      - name: {{ .Values.frontend.container.name }}
        image: "{{ .Values.frontend.container.image }}"
        ports:
        - containerPort: {{ .Values.frontend.container.port }}