apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filmcomments.fullname" . }}-db-data-pvc
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClassName }}