apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  postgres-db: {{ .Values.secret.postgresDb | b64enc }}
  postgres-user: {{ .Values.secret.postgresUser | b64enc }}
  postgres-password: {{ .Values.secret.postgresPassword | b64enc }}
  service-account-key.json: {{ .Values.secret.serviceAccountKey | b64enc }}