apiVersion: v1
kind: Service
metadata:
  name: {{ include "filmcomments-chart.fullname" . }}-frontend-service
spec:
  selector:
    app: {{ .Values.frontend.selector.app }}
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
  type: {{ .Values.frontend.service.type }}